In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/Lenovo/Desktop/my Projects/Ecommerce_data.csv")
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,01-01-2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,01-02-2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,01-03-2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,01-04-2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,01-05-2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [5]:
df.shape

(5000, 12)

In [23]:
# Expolore data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        1977 non-null   datetime64[us]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
 12  Year              1977 non-null   float64
 13  Month             1977 non-null   str
dtypes: datetime64[us](1), float64(5), int64(4), str(4)
memory usage: 547.0 KB

In [7]:
df.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

In [8]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='str')

In [9]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [14]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        1977 non-null   datetime64[us]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(4), str(3)
memory usage: 468.9 KB

In [19]:
df["Year"] = df["order_date"].dt.year

In [20]:
df["Month"] = df["order_date"].dt.month_name()

In [22]:
# revenue by region
region_sales = df.groupby("region")["revenue"].sum()

print(region_sales)

region
East     1236044.23
North    1281508.45
South    1246640.90
West     1345582.16
Name: revenue, dtype: float64

In [24]:
# Top customers
top_customers = (
    df.groupby("customer_id")["revenue"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

print(top_customers)

customer_id
1663    17680.69
1955    16265.15
1675    15036.46
1276    15023.71
1647    14894.97
1804    14330.98
1193    14151.65
1836    14110.78
1957    13956.95
1735    13146.25
Name: revenue, dtype: float64

In [25]:
# save cleared data
df.to_csv("C:/Users/Lenovo/Desktop/my Projects/cleaned_ecommerce_data.csv", index=False)

In [26]:
# Monthly sales
monthly_sales = (
    df.groupby(df["order_date"].dt.month_name())["revenue"]
      .sum()
)

print(monthly_sales)

order_date
April        161767.95
August       180697.73
December     131322.00
February     183062.00
January      163403.99
July         173858.23
June         179548.48
March        164003.98
May          182267.76
November     168512.84
October      161670.74
September    166411.40
Name: revenue, dtype: float64

In [27]:
# Average revenue
average_revenue = df["revenue"].mean()

print(average_revenue)

1021.955148

In [28]:
# Highest revenue category
top_category = (
    df.groupby("product_category")["revenue"]
      .sum()
      .sort_values(ascending=False)
)

print(top_category.head())

product_category
Electronics    1829899.22
Clothing       1531931.72
Home            982083.92
Beauty          765860.88
Name: revenue, dtype: float64